version: "3.1"
services:
  app:
    build: .
    container_name: price-save-app
    working_dir: /app
    volumes:
      - ./src:/app
      - .:/data
    environment:
      DB: ${DB_NAME}
      PORT: ${DB_PORT}
      HOST: ${DB_HOST}
      USER: ${DB_USER}
      PASS: ${DB_PASS}
      FILE: ${FILE_DATA}
